reformatted+shellchek user-manual files

diff --git a/user-doc/extract b/user-doc/extract
--- a/user-doc/extract
+++ b/user-doc/extract
@@ -1,5 +1,8 @@
 #! /usr/bin/env bash
+# using  shellchek v0.9.0
+# formatted with shfmt v3.6.0
 
+# shellcheck disable=SC1091
 source ../sourceme.sh
 
 # initial cleanup
@@ -8,62 +11,61 @@ rm -rf automatic example-check
 mkdir automatic
 mkdir example-check
 
-
 # Check for files that register actions with no documentation
-for file in ../src/*/*.cpp
-do
-  nreg=`grep "PLUMED_REGISTER_ACTION" $file | wc -l | awk '{print $1}'`
-  if [ $nreg -gt 0 ] ; then
-       ndoc=`grep PLUMEDOC $file | wc -l | awk '{print $1}'`
-       if [ $ndoc -eq 0 ] ; then
-          echo The following file registered an action but provided no documentation: $file >> errors
-       fi
-  fi 
+for file in ../src/*/*.cpp; do
+  nreg=$(grep -c "PLUMED_REGISTER_ACTION" "$file")
+  if [[ $nreg -gt 0 ]]; then
+    ndoc=$(grep -c "PLUMEDOC" "$file")
+    if [[ $ndoc -eq 0 ]]; then
+      echo "The following file registered an action but provided no documentation: $file" >>errors
+    fi
+  fi
 done
 
 # Create the list of codes that plumed works with from the set of available patches
-for file in ../patches/*.diff
-do
-   myengine=`echo "$file" | sed -e 's/.diff//' | sed -e 's/..\/patches\///'`
-   mytag=`echo "$myengine" | sed -e 's/\./-/g'`
-   echo "- $mytag" >> automatic/CODESL.list # list only, for Intro
-   echo "- \subpage $mytag " >> automatic/CODES.list
-   echo "/**" >> automatic/$myengine.txt
-   echo "\page $mytag $myengine" >> automatic/$myengine.txt
-   ../src/lib/plumed --no-mpi patch -e $myengine -i -q >> automatic/$myengine.txt
-   echo "*/" >> automatic/$myengine.txt 
+for file in ../patches/*.diff; do
+  myengine=$(echo "$file" | sed -e 's/.diff//' | sed -e 's/..\/patches\///')
+  mytag=${myengine/./-/}
+  echo "processing $myengine" >&2
+  echo "- $mytag" >>automatic/CODESL.list # list only, for Intro
+  echo "- \subpage $mytag " >>automatic/CODES.list
+  {
+    echo "/**"
+    echo "\page $mytag $myengine"
+    ../src/lib/plumed --no-mpi patch -e "$myengine" -i -q
+    echo "*/"
+  } >"automatic/$myengine.txt"
 done
 
 # Generate all the documentation pages from comments
 {
-cat ../*/*/*cpp
-# documentation for scripts:
-for file in ../scripts/*.sh
-do
-  name=$(basename ${file%.sh})
-  cat << EOF
+  cat ../*/*/*.cpp
+  # documentation for scripts:
+  for file in ../scripts/*.sh; do
+    name=$(basename "${file%.sh}")
+    cat <<EOF
 //+PLUMEDOC TOOLS $name
 /*
 EOF
-  ../src/lib/plumed $name --description
+    ../src/lib/plumed "$name" --description
 
-  cat << EOF
+    cat <<EOF
 
 \note This command line tool is implemented as a shell script. Its help message is pasted below:
 
 \verbatim
 EOF
-  ../src/lib/plumed --no-mpi $name --help
-  cat << EOF
+    ../src/lib/plumed --no-mpi "$name" --help
+    cat <<EOF
 \endverbatim
 */
 //+ENDPLUMEDOC
 EOF
 
-done
+  done
 
 } |
-awk 'BEGIN{gfile="automatic/GLOSSARY.list"; dfile="automatic/DICTIONARY.list"; }{
+  awk 'BEGIN{gfile="automatic/GLOSSARY.list"; dfile="automatic/DICTIONARY.list"; }{
   if($1=="//+ENDPLUMEDOC" && inside){
      inside=0;
      module=0
@@ -169,11 +171,11 @@ awk 'BEGIN{gfile="automatic/GLOSSARY.list"; dfile="automatic/DICTIONARY.list"; }
 }'
 
 # Now put all list files in alphabetical order
-for file in automatic/*.list ; do
+for file in automatic/*.list; do
 
-# -k 5 is required to mix together refs and subpages
-  sort -k 5 $file | uniq > $file-1
-  mv $file-1 $file
+  # -k 5 is required to mix together refs and subpages
+  sort -k 5 "$file" | uniq >"$file-1"
+  mv "$file-1" "$file"
 done
 
 # The following are not proper "list" files so should be generated after sorting
@@ -181,37 +183,37 @@ done
 long_version="$(../src/lib/plumed --no-mpi info --long-version)"
 git_version="$(../src/lib/plumed --no-mpi info --git-version)"
 
-cat > automatic/VERSION.list << EOF
+cat >automatic/VERSION.list <<EOF
 This manual has been compiled from PLUMED version <b> $long_version </b>
 (git version: <b> $git_version </b>).
 EOF
 
-if test "$TRAVIS" == true ; then
-cat >> automatic/VERSION.list << EOF
+if test "$TRAVIS" == true; then
+  cat >>automatic/VERSION.list <<EOF
 Manual built on Travis CI for branch $TRAVIS_BRANCH.
 EOF
 fi
 
-if test "$GITHUB_ACTIONS" == true ; then
-cat >> automatic/VERSION.list << EOF
+if test "$GITHUB_ACTIONS" == true; then
+  cat >>automatic/VERSION.list <<EOF
 Manual built on GitHub Actions on ref $GITHUB_REF.
 EOF
 fi
 
-if test -d regtests ; then
-cat >> automatic/VERSION.list << EOF
+if test -d regtests; then
+  cat >>automatic/VERSION.list <<EOF
 
 Regtest results for this version can be found <a href="../regtests/report.html">here</a>.
 EOF
 fi
 
-for file in ../CHANGES/* ; do
-echo "- Changes for \\subpage $(cat $file | grep "@page" | awk '{print $2}')"
-done > automatic/CHANGES.list
+for file in ../CHANGES/*; do
+  echo "- Changes for \\subpage $(cat $file | grep "@page" | awk '{print $2}')"
+done >automatic/CHANGES.list
 
 touch automatic/PDFMANUAL.list
-if test "$make_pdfdoc" = yes ; then
-cat >> automatic/PDFMANUAL.list << EOF
+if test "$make_pdfdoc" = yes; then
+  cat >>automatic/PDFMANUAL.list <<EOF
 \htmlonly
 An experimental PDF copy of this manual can be found
 <a href="../manual.pdf"> here</a>, but the html documentation should 
@@ -232,110 +234,108 @@ fi
 
 # Generate links to standard tutorial pages
 # for file in ./tutorials/*.txt ; do
-# 
-#     link=`grep link: $file | sed -e 's/link://' | sed -e 's/\@/\\\/'`
-#     describe=`grep description: $file | sed -e 's/description://'`
-# 
-#     echo "<tr> <td> $link </td> <td> $describe </td> </tr>" >> automatic/TUTORIALS.list  
+#
+#     link=$(grep link: $file | sed -e 's/link://' | sed -e 's/\@/\\\/')
+#     describe=$(grep description: $file | sed -e 's/description://')
+#
+#     echo "<tr> <td> $link </td> <td> $describe </td> </tr>" >> automatic/TUTORIALS.list
 #     # This tests the examples in the tutorials
-#     splits=`echo $file | sed -e 's/\// /g'`
-#     nf=`echo $splits | awk '{print NF}'`
-#     fname=`echo $splits | awk -v n=$nf '{print $n}'`
+#     splits=$(echo $file | sed -e 's/\// /g')
+#     nf=$(echo $splits | awk '{print NF}')
+#     fname=$(echo $splits | awk -v n=$nf '{print $n}')
 #     cp $file automatic/$fname
 #     ./test_examples automatic/$fname
-# 
+#
 # done
-# 
+#
 # # Generate links to old tutorial pages
 # for file in ./tutorials/old_tutorials/*.txt ; do
-# 
-#     link=`grep link: $file | sed -e 's/link://' | sed -e 's/\@/\\\/'`
-#     describe=`grep description: $file | sed -e 's/description://'`
-# 
-#     echo "<tr> <td> $link </td> <td> $describe </td> </tr>" >> automatic/OLDTUTORIALS.list  
+#
+#     link=$(grep link: $file | sed -e 's/link://' | sed -e 's/\@/\\\/')
+#     describe=$(grep description: $file | sed -e 's/description://')
+#
+#     echo "<tr> <td> $link </td> <td> $describe </td> </tr>" >> automatic/OLDTUTORIALS.list
 #     # This tests the examples in the tutorials
-#     splits=`echo $file | sed -e 's/\// /g'`
-#     nf=`echo $splits | awk '{print NF}'`
-#     fname=`echo $splits | awk -v n=$nf '{print $n}'`
-#     cp $file automatic/$fname 
+#     splits=$(echo $file | sed -e 's/\// /g')
+#     nf=$(echo $splits | awk '{print NF}')
+#     fname=$(echo $splits | awk -v n=$nf '{print $n}')
+#     cp $file automatic/$fname
 #     ./test_examples automatic/$fname
-# 
+#
 # done
-# 
+#
 # # Generate links to websites
 # for file in ./tutorials/*.site; do
-# 
-#    link=`grep link: $file | sed -e 's/link://'  | sed -e 's/\@/\\\/'`
-#    describe=`grep description: $file | sed -e 's/description://'`
-# 
+#
+#    link=$(grep link: $file | sed -e 's/link://'  | sed -e 's/\@/\\\/')
+#    describe=$(grep description: $file | sed -e 's/description://')
+#
 #    echo "<tr> <td> $link </td> <td> $describe </td> </tr>" >> automatic/WEBSITES.list
 #    # This tests the examples in the tutorials
-#    splits=`echo $file | sed -e 's/\// /g'`
-#    nf=`echo $splits | awk '{print NF}'`
-#    fname=`echo $splits | awk -v n=$nf '{print $n}'`
-#    cp $file automatic/$fname 
+#    splits=$(echo $file | sed -e 's/\// /g')
+#    nf=$(echo $splits | awk '{print NF}')
+#    fname=$(echo $splits | awk -v n=$nf '{print $n}')
+#    cp $file automatic/$fname
 #    ./test_examples automatic/$fname
-# 
+#
 # done
 
 # Generate links for module specific tutorials
 # for file in ./tutorials/others/*.txt ; do
-# 
-#     arrIN=(${file//.\/tutorials\/others\// }); 
-#     temp=$(echo $arrIN | tr "-" "\n"); 
+#
+#     arrIN=(${file//.\/tutorials\/others\// });
+#     temp=$(echo $arrIN | tr "-" "\n");
 #     modtut=$(echo $temp | awk '{print toupper($1)}')
-# 
-#     link=`grep link: $file | sed -e 's/link://' | sed -e 's/\@/\\\/'`
-#     describe=`grep description: $file | sed -e 's/description://'`
-# 
-#     echo "<tr> <td> $link </td> <td> $describe </td> </tr>" >> automatic/"$modtut"_TUTORIALS.list  
-# 
-#     splits=`echo $file | sed -e 's/\// /g'`
-#     nf=`echo $splits | awk '{print NF}'`
-#     fname=`echo $splits | awk -v n=$nf '{print $n}'`
-#     cp $file automatic/$fname 
+#
+#     link=$(grep link: $file | sed -e 's/link://' | sed -e 's/\@/\\\/')
+#     describe=$(grep description: $file | sed -e 's/description://')
+#
+#     echo "<tr> <td> $link </td> <td> $describe </td> </tr>" >> automatic/"$modtut"_TUTORIALS.list
+#
+#     splits=$(echo $file | sed -e 's/\// /g')
+#     nf=$(echo $splits | awk '{print NF}')
+#     fname=$(echo $splits | awk -v n=$nf '{print $n}')
+#     cp $file automatic/$fname
 #    ./test_examples automatic/$fname
 # done
-
 
 # Find what modules the user has installed
 # Find the list of modules
 # if [ -d ../mymodules ] ;  then
 #  sed -i '' -e 's/type="user" visible="no" url="mymodules.html"/type="user" visible="yes" url="mymodules.html"/' PlumedLayout.xml
-echo "<table align=center frame=void width=65%% cellpadding=5%%>" > automatic/MODULES.list
-echo "<tr> <td> <b> Module name </b> </td> <td> <b> Default behavior </b> </td> </tr>" >> automatic/MODULES.list
-for file in `ls ../src/*/module.type | sed -e 's/..\/src\///' | sed -e 's/\/module.type//'`
-do
-   defoff=0
-   dstr=`head ../src/$file/module.type`
-   if [ "$dstr" != "always" ] ; then
-         echo "<tr> <td> $file </td>" >> automatic/MODULES.list
-         if [ "$dstr" == "default-on" ] ; then
-            echo "<td> on </td> </tr>" >> automatic/MODULES.list
-         else 
-            echo "<td> off </td> </tr>" >> automatic/MODULES.list
-            defoff=1
-         fi
-#        # Generate documentation and accreditation on modules page
-#        echo "\section $file" >> automatic/mymodules.list
-#        echo >> automatic/mymodules.list
-#        echo "<table  align=center frame=void width=95%% celpadding=5%%>" >> automatic/mymodules.list
-#        echo "<tr> <td width=70%%> </td> </tr> <td>" >> automatic/mymodules.list
-#        author=`grep AUTHOR: ../mymodules/available-modules/"$file" | sed -e 's/AUTHOR://'` 
-#        echo "<b> author: $author </b>" >> automatic/mymodules.list
-#        echo "</td> </tr>" >> automatic/mymodules.list
-#        echo "<tr> <td colspan="2">" >> automatic/mymodules.list
-#        dline=`grep -n DESCRIPTION: ../mymodules/available-modules/"$file" | sed -n 's/^\([0-9]*\)[:].*/\1/p'` >> automatic/mymodules.list
-#        tail -n +$(($dline+1)) ../mymodules/available-modules/"$file" >> automatic/mymodules.list
-#        echo "</td> </tr> </table>" >> automatic/mymodules.list
-#        echo >> automatic/mymodules.list
-#        echo >> automatic/mymodules.list
-        
-        # Find src files in module and add a link to the module description
-        docfiles=$(cat ../src/"$file"/*cpp | grep PLUMEDOC | grep -v END | awk '{print $3;}')
-        for docfile in $docfiles ; do
-          cat automatic/"$docfile".tmp |
-          awk -v o=$defoff '{ print }
+echo "<table align=center frame=void width=65%% cellpadding=5%%>" >automatic/MODULES.list
+echo "<tr> <td> <b> Module name </b> </td> <td> <b> Default behavior </b> </td> </tr>" >>automatic/MODULES.list
+for file in $(find ../src/*/module.type | sed -e 's/..\/src\///' | sed -e 's/\/module.type//'); do
+  defoff=0
+  dstr=$(head "../src/$file/module.type")
+  if [ "$dstr" != "always" ]; then
+    echo "<tr> <td> $file </td>" >>automatic/MODULES.list
+    if [ "$dstr" == "default-on" ]; then
+      echo "<td> on </td> </tr>" >>automatic/MODULES.list
+    else
+      echo "<td> off </td> </tr>" >>automatic/MODULES.list
+      defoff=1
+    fi
+    #        # Generate documentation and accreditation on modules page
+    #        echo "\section $file" >> automatic/mymodules.list
+    #        echo >> automatic/mymodules.list
+    #        echo "<table  align=center frame=void width=95%% celpadding=5%%>" >> automatic/mymodules.list
+    #        echo "<tr> <td width=70%%> </td> </tr> <td>" >> automatic/mymodules.list
+    #        author=$(grep AUTHOR: ../mymodules/available-modules/"$file" | sed -e 's/AUTHOR://')
+    #        echo "<b> author: $author </b>" >> automatic/mymodules.list
+    #        echo "</td> </tr>" >> automatic/mymodules.list
+    #        echo "<tr> <td colspan="2">" >> automatic/mymodules.list
+    #        dline=$(grep -n DESCRIPTION: ../mymodules/available-modules/"$file" | sed -n 's/^\([0-9]*\)[:].*/\1/p') >> automatic/mymodules.list
+    #        tail -n +$(($dline+1)) ../mymodules/available-modules/"$file" >> automatic/mymodules.list
+    #        echo "</td> </tr> </table>" >> automatic/mymodules.list
+    #        echo >> automatic/mymodules.list
+    #        echo >> automatic/mymodules.list
+
+    # Find src files in module and add a link to the module description
+    docfiles=$(cat ../src/"$file"/*cpp | grep PLUMEDOC | grep -v END | awk '{print $3;}')
+    for docfile in $docfiles; do
+      cat "automatic/${docfile}.tmp" |
+        awk -v o=$defoff '{ print }
           /\\page '$docfile'/{
             if( o==0 ){
                 print "<table  align=center frame=void width=95%% celpadding=5%%>"
@@ -353,112 +353,105 @@ do
                 print "</td> </tr>"
                 print "</table>"
             }
-          }' > automatic/"$docfile"1.tmp
-          mv automatic/"$docfile"1.tmp automatic/"$docfile".tmp
-        done
-   fi 
+          }' >"automatic/${docfile}1.tmp"
+      mv "automatic/${docfile}1.tmp" "automatic/${docfile}.tmp"
+    done
+  fi
 done
-echo "</table>" >> automatic/MODULES.list
+echo "</table>" >>automatic/MODULES.list
 # fi
 
 # Generate all the documentation from keywords
-for file in automatic/*.tmp
-do
+for file in automatic/*.tmp; do
   # Test the example input files
-  ./test_examples $file
+  ./test_examples "$file"
   flag=${file#automatic/}
-  flag=${flag/.tmp}
-  if grep -q '//+PLUMEDOC INTERNAL' $file 1>/dev/null 2>/dev/null ; then
-       cp $file automatic/$flag.txt
+  flag=${flag/.tmp/}
+  if grep -q '//+PLUMEDOC INTERNAL' "$file" 1>/dev/null 2>/dev/null; then
+    cp "$file" "automatic/${flag}.txt"
   else
-     if ! ../src/lib/plumed --no-mpi manual --action=$flag > automatic/$flag.man 2> /dev/null ; then 
-        echo Full manual for action $flag will not be generated as you are building the manual from a code where this action was not compiled >> errors
-     elif ! grep -q "\par Examples" $file 1>/dev/null 2>/dev/null
-     then
-       echo There are no examples inside documentation for action: $flag >> errors
-     fi
-       { 
-        awk '{if($1!="*/"){print $0}}END{print "\\par Glossary of keywords and components"}' automatic/$flag.tmp
-        awk '{print $0}END{print "*/"}' automatic/$flag.man
-       } > automatic/$flag.txt
-   fi
+    if ! ../src/lib/plumed --no-mpi manual --action="$flag" >"automatic/${flag}.man" 2>/dev/null; then
+      echo "Full manual for action $flag will not be generated as you are building the manual from a code where this action was not compiled" >>errors
+    elif ! grep -q "\par Examples" "$file" 1>/dev/null 2>/dev/null; then
+      echo "There are no examples inside documentation for action: $flag" >>errors
+    fi
+    {
+      awk '{if($1!="*/"){print $0}}END{print "\\par Glossary of keywords and components"}' "automatic/${flag}.tmp"
+      awk '{print $0}END{print "*/"}' "automatic/${flag}.man"
+    } >"automatic/${flag}.txt"
+  fi
 done
 
 sed -ie 's/<b> --/<b> \\c \\-\\-/g' automatic/*.txt
 rm automatic/*.txte
 
 for file in COLVAR MCOLVAR MFILTERS MTRANSFORMS VOLUMES DCOLVAR MCOLVARF MCOLVARB ANALYSIS LANDMARKS MATRIX MATRIXF CONCOMP REWEIGHTING PRINTANALYSIS BIAS GLOSSARY \
-            DICTIONARY WEBSITES FUNCTION TOPOLOGY VATOM GRIDCALC GRIDANALYSIS DIMRED \
-            TOOLS
-do
+  DICTIONARY WEBSITES FUNCTION TOPOLOGY VATOM GRIDCALC GRIDANALYSIS DIMRED \
+  TOOLS; do
   mv automatic/$file.list automatic/$file.1.list
   {
     echo "<table align=center frame=void width=95%% cellpadding=5%%>"
     cat automatic/$file.1.list
     echo "</table>"
-  } > automatic/$file.list
+  } >automatic/$file.list
   rm automatic/$file.1.list
 done
 
-for file in automatic/*_*.list
-do
-  mv $file $file.1
+for file in automatic/*_*.list; do
+  mv "$file" "$file.1"
   {
     echo "<table align=center frame=void width=95%% cellpadding=5%%>"
-    cat $file.1
+    cat "$file.1"
     echo "</table>"
-  } > $file
-  rm $file.1
+  } >"$file"
+  rm "$file.1"
 done
 
-for file in automatic/*_OTHERMODULES.list
-do
+for file in automatic/*_OTHERMODULES.list; do
 
-ff=${file%_OTHERMODULES.list}.list
+  ff=${file%_OTHERMODULES.list}.list
 
-if test -f "$ff" ; then
+  if test -f "$ff"; then
 
-mv $ff $ff.1
-  {
-    cat $ff.1
-    echo "In addition to the keywords above, by enabling optional modules you can access to the following keywords:"
-    cat $file
-  } > $ff
-fi
+    mv "$ff" "$ff.1"
+    {
+      cat "$ff.1"
+      echo "In addition to the keywords above, by enabling optional modules you can access to the following keywords:"
+      cat "$file"
+    } >"$ff"
+  fi
 done
 
 # Make all double hyphens appear as double hypens
 sed -ie 's/<b> --/<b> \\c \\-\\-/g' automatic/*.txt
 rm automatic/*.txte
 
-rm -f *PP.txt *PP.md
+rm -f ./*PP.txt ./*PP.md
 
-keywords=`grep "@[A-Z0-9_]*@" *.md | awk -F"@" '{print $2}' | sort | uniq`
+keywords=$(grep "@[A-Z0-9_]*@" *.md | awk -F"@" '{print $2}' | sort | uniq)
 
-for f in *.txt *.md
-do
+for f in *.txt *.md; do
 
-test -f $f || continue
+  test -f "$f" || continue
 
-extension=${f##*.}
+  extension=${f##*.}
 
-file=${f%.$extension}
+  file=${f%."$extension"}
 
-# first replace with the content of the files
-# then grep out the special strings
+  # first replace with the content of the files
+  # then grep out the special strings
 
-cp $f ${file}PP.$extension
-./test_examples ${file}PP.$extension
+  cp "$f" "${file}PP.$extension"
+  ./test_examples "${file}PP.$extension"
 
-for kk in $keywords
-do
-  sed -ie "
+  for kk in $keywords; do
+    sed -ie "
     /^ *@"$kk"@ *$/r     automatic/$kk.list
-" ${file}PP.$extension
-done
-rm -f *."$extension"e
+" "${file}PP.$extension"
+  done
+  rm -f ./*."$extension"e
 
-grep -Ev '^ *@[A-Z0-9:_]*@ *$' ${file}PP.$extension > tmp;
-mv tmp ${file}PP.$extension
+  grep -Ev '^ *@[A-Z0-9:_]*@ *$' "${file}PP.$extension" >tmp
+  mv tmp "${file}PP.$extension"
 
 done
diff --git a/user-doc/go-doxygen b/user-doc/go-doxygen
--- a/user-doc/go-doxygen
+++ b/user-doc/go-doxygen
@@ -1,14 +1,17 @@
 #! /usr/bin/env bash
+# using  shellchek v0.9.0
+# formatted with shfmt v3.6.0
 
+# shellcheck disable=SC1091
 source ../sourceme.sh
 
-if plumed --no-mpi config mpiexec ; then
-   mpirun=$(plumed --no-mpi config mpiexec)
+if plumed --no-mpi config mpiexec; then
+  mpirun=$(plumed --no-mpi config mpiexec)
 else
-   mpirun=mpirun
+  mpirun=mpirun
 fi
 
-LISTMORE=`ls *PP.md | grep -wvFf basic.list`
+LISTMORE=$(find ./*PP.md | grep -wvFf basic.list)
 
 LIST="
  IntroductionPP.md
@@ -32,12 +35,12 @@ LIST="
  GlossaryPP.md
  automatic"
 
-echo $LIST
+echo "$LIST"
 
 {
   cat Doxyfile
   echo "PROJECT_NUMBER = \"$(../src/lib/plumed --no-mpi info --long-version)\""
-  echo "INPUT+=" $LIST
+  echo "INPUT+= $LIST"
   # add this to manually control layout:
   # echo "LAYOUT_FILE=PlumedLayout.xml"
 } | doxygen -
@@ -46,12 +49,12 @@ version=v$(../src/lib/plumed --no-mpi info --version)
 
 # in the online manual better to put the branch name
 # which is available through the TRAVIS_BRANCH env var
-if test "$TRAVIS" == true ; then
+if test "$TRAVIS" == true; then
   version="${TRAVIS_BRANCH}"
 fi
 
-if test "$GITHUB_ACTIONS" == true ; then
-  if [[ "$GITHUB_REF" == "refs/heads/"* ]] ; then
+if test "$GITHUB_ACTIONS" == true; then
+  if [[ "$GITHUB_REF" == "refs/heads/"* ]]; then
     version="${GITHUB_REF#refs/heads/}"
   fi
 fi
@@ -59,13 +62,18 @@ fi
 # THIS IS FOR DOXYGEN <= 1.8.10
 # I leave it here for the moment
 mkdir build_examples
-cd build_examples
+cd build_examples || {
+  echo "failure in cd to build_examples"
+  exit 1
+}
 mkdir build
-cd build
-for file in ../../html/*.html
-do
-echo final processing of html for file: $file
-gawk -v version="$version" '{
+cd build || {
+  echo "failure in cd to build_examples/build"
+  exit 1
+}
+for file in ../../html/*.html; do
+  echo "final processing of html for file: $file"
+  gawk -v version="$version" '{
   if(match($0,"<span>Main&#160;Page</span>")){
     sub("Main","Home",$0);
     sub("Page","("version")",$0);
@@ -104,21 +112,21 @@ gawk -v version="$version" '{
     print "   }"
     print "</script>"
   } else print
-}' $file > tmp
-gawk -v mpirun="$mpirun" -f ../../plumed-syntax.awk tmp > $file.tmp
-if [ $? -ne 0 ]; then
-   echo "ERROR IN RUNNING PLUMED SYNTAX COMMAND ON " $file
-   exit
-fi
-mv $file.tmp $file
-rm -fr *
+}' "$file" >tmp
+  gawk -v mpirun="$mpirun" -f ../../plumed-syntax.awk tmp >"$file.tmp"
+  if [ $? -ne 0 ]; then
+    echo "ERROR IN RUNNING PLUMED SYNTAX COMMAND ON $file"
+    exit
+  fi
+  mv "$file.tmp" "$file"
+  rm -fr ./*
 done
 cd ../../
 rm -rf build_examples
 # end of DOXYGEN <=1.8.10
 
 # Same stuff for DOXYGEN >=1.8.12
-cat > html/menudata.js << EOF
+cat >html/menudata.js <<EOF
 var menudata={children:[
 {text:'Home ($version)',url:'index.html'},
 {text:'Getting Started',url:'_syntax.html'},
@@ -128,18 +136,19 @@ var menudata={children:[
 EOF
 # end of DOXYGEN >=1.8.12
 
-cat html/doxygen.css plumed.css > html/doxygen.css.tmp
+cat html/doxygen.css plumed.css >html/doxygen.css.tmp
 mv html/doxygen.css.tmp html/doxygen.css
+# shellcheck disable=SC2154
+if [[ $make_pdfdoc == yes ]]; then
 
-if [ "$make_pdfdoc" != yes ] ; then
-  exit
+  cd latex || {
+    echo "failure in cd to latex"
+    exit 1
+  }
+
+  # this is a workaround for a problem on the linux workstation
+  # where I compile the manual - GB
+  sed -ie 's/pdfencoding=unicode/unicode/g' refman.tex
+  make -i
+  cp refman.pdf ../manual.pdf
 fi
-
-cd latex
-
-# this is a workaround for a problem on the linux workstation
-# where I compile the manual - GB
-sed -ie 's/pdfencoding=unicode/unicode/g' refman.tex
-make -i
-cp refman.pdf ../manual.pdf
-
